// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTA1zIbSBE5sg27fuJQPABEwm-lVZVYcU',
    appId: '1:1051392765409:web:943893d03705ea45c4b6a0',
    messagingSenderId: '1051392765409',
    projectId: 'travelrecommendation-851e9',
    authDomain: 'travelrecommendation-851e9.firebaseapp.com',
    storageBucket: 'travelrecommendation-851e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJOmv4azxAIiKVuN4Bcm_CI1C3vxe7nQ',
    appId: '1:1051392765409:android:13d0ad863bb0bab3c4b6a0',
    messagingSenderId: '1051392765409',
    projectId: 'travelrecommendation-851e9',
    storageBucket: 'travelrecommendation-851e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sVi-eKXhvc5f_vjFEr68wKTg46fX6Cg',
    appId: '1:1051392765409:ios:61414d05924ead0ac4b6a0',
    messagingSenderId: '1051392765409',
    projectId: 'travelrecommendation-851e9',
    storageBucket: 'travelrecommendation-851e9.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTA1zIbSBE5sg27fuJQPABEwm-lVZVYcU',
    appId: '1:1051392765409:web:9187d25d00ae628cc4b6a0',
    messagingSenderId: '1051392765409',
    projectId: 'travelrecommendation-851e9',
    authDomain: 'travelrecommendation-851e9.firebaseapp.com',
    storageBucket: 'travelrecommendation-851e9.firebasestorage.app',
  );
}
